#!/usr/bin/env bash
total=0
files=3
for i in {1..3}
do
    echo "Running packets$[i].txt on rules$[i].txt"
    cat packets$[i+0].txt | ./fw rules$[i].txt > test-result$[i].txt
    count=$(cmp test-result$[i].txt results$[i].txt | wc -l)
    if [ "$count" == "0" ]
    then
        echo "Diff: SUCCESS"
        ((total++))
    else
        echo "Diff: $(cmp test-result$[i].txt results$[i].txt)"
    fi
    echo "---"
done
echo "Status: $total/$files passed"
